language: python
python:
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - python setup.py install
  - pip install coverage codecov
# command to run tests
script:
  - coverage run -m unittest discover -s src
after_success:
  - codecov
